### ISSUE TITLE
Add custom class to figure

### ISSUE THREAD

**Issue by austincondiff** [leonardodino/gatsby-remark-figure-caption#4]
In my markdown I'd like to specify a class to add to the figure so I can float it to the left or right.

**Comment by leonardodino** [comment]
I understand the request, but there's no way of adding custom classes in markdown. besides writing plain html :/

how the syntax for that is supposed to look like?

**Comment by austincondiff** [comment]
I am trying to do something like Medium where you can have an image inset-left, centered, inset-right, outset-left, outset-centered, outset-right or full-width. 

I can do this several ways. The first method involves appending a layout to the url for example, `![](http://lorempixel.com/400/200#insetLeft)`, then I can target it with css like so...

```css
.post-content img[src*='#insetLeft'] {
  float: left;
  margin-right: 30px;
  padding-top: 1rem;
  padding-bottom: 1rem;
  width: auto;
  max-width: 50%;
}
```

The next method I can use the `gatsby-remark-attr` package to do something like this...
`![](http://lorempixel.com/400/200){class="insetLeft"}`
Then I would do...
```css
.post-content img.insetLeft {
  float: left;
  margin-right: 30px;
  padding-top: 1rem;
  padding-bottom: 1rem;
  width: auto;
  max-width: 50%;
}
```

Then I realized that I want to have a caption underneath the image (also like Medium does). The first method targets the `src` attr. The second puts a class on the image (It doesn't with your package). Because there is no parent selector in css, I cannot do either with a caption. The only way is if I were to do the second approach and the figure element inherited the same class that the image would have gotten.

I would ask if you can check the image to see if it has gotten any other classes and apply those to the figure. You allow a class to be put on figure, but it is very static as it is set via the options.

Here is an example of a page where I am using most layout types. I can't use a caption here because it won't align with the image. [Check it out](http://austincondiff.com/lds-org-prototype/news/updated-media-library-app). You can inspect the images to see what I am talking about. The first image has a caption as well and you can see what happens.
